### ISSUE TITLE
Missing data values

### ISSUE THREAD

**Issue by huyen-nguyen** [vast-challenge/2020-sample-data#1]
Hello,

In the MC2-Image-Data dataset, some CSV data files describing images contain missing data values or values in the wrong format, e.g., the **x and y coordinates** from files Person3_25.csv, Person40_1.csv to Person40_4.csv.

Could you let me know if that is intentional for the dataset?

Thank you!
 
Attached images:
1) Read file by Sublime
![image](https://user-images.githubusercontent.com/22818938/79103659-36bb4e00-7d97-11ea-84b7-8d498276e309.png)

2) Read file by Jupyter Lab
![image](https://user-images.githubusercontent.com/22818938/79103588-155a6200-7d97-11ea-8195-816694f3adab.png)

**Comment by jhaack** [comment]
Thanks for filing the issue. We've added your question to the page on the challenge site at: https://vast-challenge.github.io/2020/MC2.html 

Clarification:
The image analysis process used by CGCS has limitations and imperfections. Can your tool help overcome these issues?

**Comment by huyen-nguyen** [comment]
Thank you so much for the clarification.
